### ISSUE TITLE
Usability on laptops?

### ISSUE THREAD

**Issue by Kungergely** [hensm/ddccli#1]
I have a laptop a bit on the old side (~6 years old maybe?), an HP ProBook 4340s that has an Intel HD graphics chip. Even though I can query the list of monitors fine (I get "\\.\DISPLAY1" as the display ID), I'm not able to change any of the settings (I get a "failed to set monitor brightness" or "failed to set monitor contrast" type of error). Could this be because of driver incompatibility issues (I have Windows 7 and the associated functions e.g. GetMonitorContrast() and SetMonitorContrast() should work fine from Vista onwards)?

**Comment by hensm** [comment]
As long as you're changing settings for an external monitor with DDC/CI support (and enabled), it should work fine. Internal laptop displays use a different protocol, so that won't work.

**Comment by Kungergely** [comment]
Yeah, I tried to use it on the internal display of course hoping that it supports the DDC/CI protocol as well. Thanks for the info.
